name: ci
permissions:
    contents: read
on:
    push:
        branches: [master]
    pull_request:
        branches: [master]
jobs:
    test:
        name: Test (Python ${{ matrix.python }}, Solr ${{ matrix.solr }})
        strategy:
            fail-fast: false
            matrix:
                python: ["3.10", "3.11", "3.12", "3.13", "3.14", "3.14t"]
                solr: ["9", "10"]
        runs-on: ubuntu-latest
        env:
            UV_PYTHON: ${{ matrix.python }}
            SOLR_VERSION: ${{ matrix.solr }}
            UV_LOCKED: 1
            UV_NO_DEV: 1
            PYTHONUNBUFFERED: 1
        steps:
            - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
              with:
                  persist-credentials: false

            - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
              with:
                  python-version: ${{ matrix.python }}
                  allow-prereleases: true

            - name: Install uv
              uses: astral-sh/setup-uv@fac544c07dec837d0ccb6301d7b5580bf5edae39 # v8.2.0
              with:
                  version: "0.11.6"

            - name: Run tests
              run: uv run --extra=solrcloud run-tests.py
