name: ci
permissions:
    contents: read
on:
    push:
        branches: [master]
    pull_request:
        branches: [master]
jobs:
    test:
        name: Test (Python ${{ matrix.python }}, Solr ${{ matrix.solr }})
        strategy:
            fail-fast: false
            matrix:
                python: ["3.10", "3.11", "3.12", "3.13", "3.14", "3.14t"]
                solr: ["9", "10"]
        runs-on: ubuntu-latest
        env:
            UV_PYTHON: ${{ matrix.python }}
            SOLR_VERSION: ${{ matrix.solr }}
            UV_LOCKED: 1
            UV_NO_DEV: 1
            PYTHONUNBUFFERED: 1
        steps:
            - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
              with:
                  persist-credentials: false

            - uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6.3.0
              with:
                  python-version: ${{ matrix.python }}
                  allow-prereleases: true

            - name: Install uv
              uses: astral-sh/setup-uv@11f9893b081a58869d3b5fccaea48c9e9e46f990 # v8.3.2
              with:
                  version: "0.11.6"

            - name: Run tests
              run: uv run --extra=solrcloud run-tests.py
